// hskWords.js

const hskWords = {
    1: [
        { chinese: "你", pinyin: "nǐ", translation: "you", category: "pronoun" },
        { chinese: "好", pinyin: "hǎo", translation: "good", category: "adjective" },
        // Add more HSK 1 words here
    ],
    2: [
        { chinese: "爱", pinyin: "ài", translation: "love", category: "emotion" },
        { chinese: "八", pinyin: "bā", translation: "eight", category: "number" },
        { chinese: "爸爸", pinyin: "bàba", translation: "father", category: "family" },
        { chinese: "吧", pinyin: "ba", translation: "particle", category: "grammar" },
        { chinese: "白", pinyin: "bái", translation: "white", category: "color" },
        { chinese: "百", pinyin: "bǎi", translation: "hundred", category: "number" },
        { chinese: "帮助", pinyin: "bāngzhù", translation: "help", category: "action" },
        { chinese: "报纸", pinyin: "bàozhǐ", translation: "newspaper", category: "object" },
        { chinese: "杯子", pinyin: "bēizi", translation: "cup", category: "object" },
        { chinese: "北京", pinyin: "Běijīng", translation: "Beijing", category: "place" },
        { chinese: "比", pinyin: "bǐ", translation: "compare", category: "action" },
        { chinese: "别", pinyin: "bié", translation: "don't", category: "grammar" },
        { chinese: "长", pinyin: "cháng", translation: "long", category: "description" },
        { chinese: "唱歌", pinyin: "chànggē", translation: "sing", category: "action" },
        { chinese: "出", pinyin: "chū", translation: "exit", category: "action" },
        { chinese: "穿", pinyin: "chuān", translation: "wear", category: "action" },
        { chinese: "次", pinyin: "cì", translation: "time", category: "time" },
        { chinese: "从", pinyin: "cóng", translation: "from", category: "grammar" },
        { chinese: "错", pinyin: "cuò", translation: "wrong", category: "description" },
        { chinese: "打篮球", pinyin: "dǎ lánqiú", translation: "play basketball", category: "action" },
        { chinese: "大家", pinyin: "dàjiā", translation: "everyone", category: "people" },
        { chinese: "但是", pinyin: "dànshì", translation: "but", category: "grammar" },
        { chinese: "到", pinyin: "dào", translation: "arrive", category: "action" },
        { chinese: "得", pinyin: "de", translation: "particle", category: "grammar" },
        { chinese: "等", pinyin: "děng", translation: "wait", category: "action" },
        { chinese: "弟弟", pinyin: "dìdi", translation: "younger brother", category: "family" },
        { chinese: "第一", pinyin: "dì-yī", translation: "first", category: "number" },
        { chinese: "懂", pinyin: "dǒng", translation: "understand", category: "action" },
        { chinese: "对", pinyin: "duì", translation: "correct", category: "description" },
        { chinese: "房间", pinyin: "fángjiān", translation: "room", category: "place" },
        { chinese: "非常", pinyin: "fēicháng", translation: "extremely", category: "description" },
        { chinese: "服务员", pinyin: "fúwùyuán", translation: "waiter", category: "people" },
        { chinese: "高", pinyin: "gāo", translation: "tall", category: "description" },
        { chinese: "告诉", pinyin: "gàosu", translation: "tell", category: "action" },
        { chinese: "哥哥", pinyin: "gēge", translation: "older brother", category: "family" },
        { chinese: "给", pinyin: "gěi", translation: "give", category: "action" },
        { chinese: "公共汽车", pinyin: "gōnggòngqìchē", translation: "bus", category: "object" },
        { chinese: "公司", pinyin: "gōngsī", translation: "company", category: "place" },
        { chinese: "贵", pinyin: "guì", translation: "expensive", category: "description" },
        { chinese: "过", pinyin: "guò", translation: "pass", category: "action" },
        { chinese: "还", pinyin: "hái", translation: "still", category: "grammar" },
        { chinese: "孩子", pinyin: "háizi", translation: "child", category: "people" },
        { chinese: "好吃", pinyin: "hǎochī", translation: "delicious", category: "description" },
        { chinese: "号", pinyin: "hào", translation: "number", category: "number" },
        { chinese: "喝", pinyin: "hē", translation: "drink", category: "action" },
        { chinese: "和", pinyin: "hé", translation: "and", category: "grammar" },
        { chinese: "黑", pinyin: "hēi", translation: "black", category: "color" },
        { chinese: "红", pinyin: "hóng", translation: "red", category: "color" },
        { chinese: "欢迎", pinyin: "huānyíng", translation: "welcome", category: "action" },
        { chinese: "回答", pinyin: "huídá", translation: "answer", category: "action" },
        { chinese: "回", pinyin: "huí", translation: "return", category: "action" },
        { chinese: "会", pinyin: "huì", translation: "will", category: "grammar" },
        { chinese: "火车站", pinyin: "huǒchēzhàn", translation: "train station", category: "place" },
        { chinese: "机场", pinyin: "jīchǎng", translation: "airport", category: "place" },
        { chinese: "鸡蛋", pinyin: "jīdàn", translation: "egg", category: "object" },
        { chinese: "件", pinyin: "jiàn", translation: "piece", category: "measure" },
        { chinese: "教室", pinyin: "jiàoshì", translation: "classroom", category: "place" },
        { chinese: "姐姐", pinyin: "jiějie", translation: "older sister", category: "family" },
        { chinese: "介绍", pinyin: "jièshào", translation: "introduce", category: "action" },
        { chinese: "进", pinyin: "jìn", translation: "enter", category: "action" },
        { chinese: "近", pinyin: "jìn", translation: "near", category: "description" },
        { chinese: "就", pinyin: "jiù", translation: "just", category: "grammar" },
        { chinese: "觉得", pinyin: "juéde", translation: "feel", category: "emotion" },
        { chinese: "咖啡", pinyin: "kāfēi", translation: "coffee", category: "object" },
        { chinese: "开始", pinyin: "kāishǐ", translation: "start", category: "action" },
        { chinese: "考试", pinyin: "kǎoshì", translation: "exam", category: "event" },
        { chinese: "可能", pinyin: "kěnéng", translation: "possible", category: "description" },
        { chinese: "可以", pinyin: "kěyǐ", translation: "can", category: "grammar" },
        { chinese: "课", pinyin: "kè", translation: "class", category: "event" },
        { chinese: "快", pinyin: "kuài", translation: "fast", category: "description" },
        { chinese: "快乐", pinyin: "kuàilè", translation: "happy", category: "emotion" },
        { chinese: "累", pinyin: "lèi", translation: "tired", category: "description" },
        { chinese: "离", pinyin: "lí", translation: "from", category: "grammar" },
        { chinese: "两", pinyin: "liǎng", translation: "two", category: "number" },
        { chinese: "路", pinyin: "lù", translation: "road", category: "place" },
        { chinese: "旅游", pinyin: "lǚyóu", translation: "travel", category: "action" },
        { chinese: "卖", pinyin: "mài", translation: "sell", category: "action" },
        { chinese: "慢", pinyin: "màn", translation: "slow", category: "description" },
        { chinese: "忙", pinyin: "máng", translation: "busy", category: "description" },
        { chinese: "每", pinyin: "měi", translation: "every", category: "grammar" },
        { chinese: "妹妹", pinyin: "mèimei", translation: "younger sister", category: "family" },
        { chinese: "门", pinyin: "mén", translation: "door", category: "object" },
        { chinese: "男人", pinyin: "nánrén", translation: "man", category: "people" },
        { chinese: "您", pinyin: "nín", translation: "you (polite)", category: "people" },
        { chinese: "牛奶", pinyin: "niúnǎi", translation: "milk", category: "object" },
        { chinese: "女", pinyin: "nǚ", translation: "female", category: "people" },
        { chinese: "女人", pinyin: "nǚrén", translation: "woman", category: "people" },
        { chinese: "旁边", pinyin: "pángbiān", translation: "beside", category: "place" },
        { chinese: "跑步", pinyin: "pǎobù", translation: "run", category: "action" },
        { chinese: "便宜", pinyin: "piányi", translation: "cheap", category: "description" },
        { chinese: "票", pinyin: "piào", translation: "ticket", category: "object" },
        { chinese: "妻子", pinyin: "qīzi", translation: "wife", category: "family" },
        { chinese: "千", pinyin: "qiān", translation: "thousand", category: "number" },
        { chinese: "晴", pinyin: "qíng", translation: "clear (weather)", category: "description" },
        { chinese: "去年", pinyin: "qùnián", translation: "last year", category: "time" },
        { chinese: "让", pinyin: "ràng", translation: "let", category: "grammar" },
        { chinese: "日", pinyin: "rì", translation: "day", category: "time" },
        { chinese: "上班", pinyin: "shàngbān", translation: "go to work", category: "action" },
        { chinese: "身体", pinyin: "shēntǐ", translation: "body", category: "object" },
        { chinese: "生病", pinyin: "shēngbìng", translation: "fall ill", category: "action" },
        { chinese: "生日", pinyin: "shēngrì", translation: "birthday", category: "time" },
        { chinese: "时间", pinyin: "shíjiān", translation: "time", category: "time" },
        { chinese: "事情", pinyin: "shìqíng", translation: "thing", category: "object" },
        { chinese: "手表", pinyin: "shǒubiǎo", translation: "watch", category: "object" },
        { chinese: "手机", pinyin: "shǒujī", translation: "mobile phone", category: "object" },
        { chinese: "说话", pinyin: "shuōhuà", translation: "speak", category: "action" },
        { chinese: "送", pinyin: "sòng", translation: "give (as a present)", category: "action" },
        { chinese: "虽然", pinyin: "suīrán", translation: "although", category: "grammar" },
        { chinese: "它", pinyin: "tā", translation: "it", category: "people" },
        { chinese: "踢足球", pinyin: "tī zúqiú", translation: "play football", category: "action" },
        { chinese: "题", pinyin: "tí", translation: "question", category: "object" },
        { chinese: "跳舞", pinyin: "tiàowǔ", translation: "dance", category: "action" },
        { chinese: "外", pinyin: "wài", translation: "outside", category: "place" },
        { chinese: "完", pinyin: "wán", translation: "finish", category: "action" },
        { chinese: "玩", pinyin: "wán", translation: "play", category: "action" },
        { chinese: "晚上", pinyin: "wǎnshàng", translation: "evening", category: "time" },
        { chinese: "为什么", pinyin: "wèishénme", translation: "why", category: "grammar" },
        { chinese: "问", pinyin: "wèn", translation: "ask", category: "action" },
        { chinese: "问题", pinyin: "wèntí", translation: "question", category: "object" },
        { chinese: "西瓜", pinyin: "xīguā", translation: "watermelon", category: "object" },
        { chinese: "希望", pinyin: "xīwàng", translation: "hope", category: "emotion" },
        { chinese: "洗", pinyin: "xǐ", translation: "wash", category: "action" },
        { chinese: "小时", pinyin: "xiǎoshí", translation: "hour", category: "time" },
        { chinese: "笑", pinyin: "xiào", translation: "laugh", category: "action" },
        { chinese: "新", pinyin: "xīn", translation: "new", category: "description" },
        { chinese: "姓", pinyin: "xìng", translation: "surname", category: "people" },
        { chinese: "休息", pinyin: "xiūxi", translation: "rest", category: "action" },
        { chinese: "雪", pinyin: "xuě", translation: "snow", category: "weather" },
        { chinese: "眼睛", pinyin: "yǎnjīng", translation: "eye", category: "object" },
        { chinese: "羊肉", pinyin: "yángròu", translation: "lamb", category: "food" },
        { chinese: "药", pinyin: "yào", translation: "medicine", category: "object" },
        { chinese: "要", pinyin: "yào", translation: "want", category: "action" },
        { chinese: "也", pinyin: "yě", translation: "also", category: "grammar" },
        { chinese: "一下", pinyin: "yíxià", translation: "a bit", category: "description" },
        { chinese: "已经", pinyin: "yǐjīng", translation: "already", category: "grammar" },
        { chinese: "一起", pinyin: "yìqǐ", translation: "together", category: "grammar" },
        { chinese: "意思", pinyin: "yìsi", translation: "meaning", category: "object" },
        { chinese: "因为", pinyin: "yīnwèi", translation: "because", category: "grammar" },
        { chinese: "游泳", pinyin: "yóuyǒng", translation: "swim", category: "action" },
        { chinese: "右边", pinyin: "yòubiān", translation: "right side", category: "place" },
        { chinese: "鱼", pinyin: "yú", translation: "fish", category: "food" },
        { chinese: "远", pinyin: "yuǎn", translation: "far", category: "description" },
        { chinese: "运动", pinyin: "yùndòng", translation: "sport", category: "action" },
        { chinese: "再", pinyin: "zài", translation: "again", category: "grammar" },
        { chinese: "早上", pinyin: "zǎoshàng", translation: "morning", category: "time" },
        { chinese: "丈夫", pinyin: "zhàngfu", translation: "husband", category: "family" },
        { chinese: "找", pinyin: "zhǎo", translation: "look for", category: "action" },
        { chinese: "着", pinyin: "zhe", translation: "particle", category: "grammar" },
        { chinese: "真", pinyin: "zhēn", translation: "really", category: "description" },
        { chinese: "正在", pinyin: "zhèngzài", translation: "in the process of", category: "grammar" },
        { chinese: "知道", pinyin: "zhīdào", translation: "know", category: "action" },
        { chinese: "准备", pinyin: "zhǔnbèi", translation: "prepare", category: "action" },
        { chinese: "走", pinyin: "zǒu", translation: "walk", category: "action" },
        { chinese: "最", pinyin: "zuì", translation: "most", category: "description" },
        { chinese: "左边", pinyin: "zuǒbiān", translation: "left side", category: "place" }
    ],
    
    3: [
        // Add HSK 3 words here
    ],
    4: [
        // Add HSK 4 words here
    ],
    5: [
        // Add HSK 5 words here
    ],
    6: [
        // Add HSK 6 words here
    ]
};
